### ISSUE TITLE
Support for a non-Newtonsoft JSON Serializer

### ISSUE THREAD

**Issue by jenesaisdiq** [emanzione/PATCH#36]
The Newtonsoft serializer used by PATCH seems to be causing package conflicts with other assets and potentially the built-in Unity version. Rather than fighting through these, it seems easier to either replace it with another serializer altogether, or provide an alternative serializer if you have a problem. Several other JSON serializers exist, it would just be a matter of implementing them within PATCH.

**Comment by manhunterita** [comment]
I introduced a new manual JSON serialization that is built-in the PATCH core. It does not depend on any external JSON library and is not based on reflection nor on IL emitting.
Waiting for tests.
