### ISSUE TITLE
[Localization] Missing localization strings

### ISSUE THREAD

**Issue by BuckTuddrussel** [emanzione/PATCH#39]
Some strings are not exposed to translation like "Downloading", "Fixing"
![obraz](https://user-images.githubusercontent.com/38207499/112841423-bfaec080-90a0-11eb-9ef8-78ee884916eb.png)

Version: 2.5.3
Variant: Basic

**Comment by emanzione** [comment]
Added some of the missing translations. If something else misses, just report it to me!
