### ISSUE TITLE
On Mac (and maybe on Linux) the Mono Runtime fails to retrieve the remaining Disk Space

### ISSUE THREAD

**Issue by Gameplay** [emanzione/PATCH#44]
**the error is:**
System.Exception: Not enough disk space for repairing. Required space [547338323], available space [0]

The Launcher is trying to download the game folders/files but the error gets thrown in the console. I have enough space and I am on Mac (Monterey 12.1).

Kind regards,
Paul

**Comment by emanzione** [comment]
Hi Paul,
that's a problem in the Mono runtime on Mac. The only way to work around it is to disable the disk space check when on Mac: `_context.Settings.EnableDiskSpaceCheck = false;` and you will be fine to go.

**Comment by Gameplay** [comment]
Ah oke, but where do I set this? (the _context.Settings.EnableDiskSpaceCheck = false;)

**Comment by emanzione** [comment]
In `LauncherBase.cs`! You can set it in the `CreateSettings` function (by writing `settings.EnableDiskSpace = false;`) or in `CreateContext` function (by writing `context.Settings.EnableDiskSpace = false;`).

**Comment by Gameplay** [comment]
Mm oke so now I have to find a way to not edit the asset code but somehow extend/override it. Thanks for your help! I will test things out.

**Comment by emanzione** [comment]
This bugfix will be included in the next release anyway, so don't worry about that! I'll mark this as bugfix request, just to keep track of it.

**Comment by Gameplay** [comment]
Great! Thank you very much I really appreciate that.

**Comment by Gameplay** [comment]
One little off-topic question.
When I built and tested the launcher (it downloaded the game logic!) it says this in the manual (under Testing the Launcher)
"From now on you can run directly your game".

Does this mean from now on I have to start the game by using the gameName.app (or gameName.exe in Windows) or always use the LauncherName.app (or Launcher.exe in Windows)?

**Comment by emanzione** [comment]
It's up to you and how you like your game to behave. You can start your game.exe and it will redirect to launcher.exe if an update is found.
Or you can directly start launcher.exe and it will redirect to game.exe if no updates are found.

**Comment by Gameplay** [comment]
Oke sounds good. I’m Thanks again! 

ps: My comments about this can be removed. I don't want to be rude and delete them before you read this :)/

**Comment by emanzione** [comment]
No worries! Also: join us on Discord if you like! We can answer all your questions more quickly and you will be able to discuss with other customers that already work on Mac with PATCH!

**Comment by emanzione** [comment]
I improved the error detection for this particular situation. Now it tries to recognize scenarios where the feature is not supported by the OS and tries to proceed anyway.

Commit ref: [28760cda](https://gitlab.com/emanzione/mhlab.patch/-/commit/28760cdafc4124a810d4291d09fa2717ed30de7e)
