### ISSUE TITLE
(Mac) Can't update the Launcher

### ISSUE THREAD

**Issue by Gameplay** [emanzione/PATCH#45]
Updating the game via the launcher is working. But updating the Launcher itself isn't. Maybe this is because of something I noticed.

So when I build the Game (With the PreGame scene on build index 0) and start it when the building is done. It opens the PreGame scene and starts downloading the new Launcher. This is great.

But when I let the Launcher download the game logic and start the game it immediately starts the game and seems to skip the PreGame scene logic.

Any ideas of what I am doing wrong? 

ps: I uploaded the right versions.

**Comment by emanzione** [comment]
Do you upload correctly all the files needed for the Launcher self-update? `updater_index.json` too, it must be replaced every time you process a new update.
If so, make sure your web server hasn't a cache (or make sure to flush the cache too).

**Comment by Gameplay** [comment]
Yes! The webserver (AWS Cloud Front) had cache enabled. Thanks a lot! This can be marked as solved/closed

ps: for other AWS Cloud Front users, I solved this by creating an invalidation for the paths that had to stay out of the cache.
