### ISSUE TITLE
WPF Forms - Missing Namespaces (Advanced;  ChunkedDownloader)

### ISSUE THREAD

**Issue by TrickShotMLG02** [emanzione/PATCH#48]
![image](https://user-images.githubusercontent.com/43967908/161379573-02a127c2-cc0d-4508-b01c-d3d304bf61c0.png)
I am using v 2.6.1 and i got the errors above when compiling the project. I have added the 2 dll files as reference.

Any suggestions?

**Comment by emanzione** [comment]
If you are on Basic version, you haven't access to Advanced and ChunkedDownloader.
Just add the two DLLs as dependencies (like you did), then remove any other reference to Advanced project and namespaces.
