### ISSUE TITLE
Patch progress lost

### ISSUE THREAD

**Issue by TrickShotMLG02** [emanzione/PATCH#50]
I backed up my complete project, made a script upgrade due to an old api version of an imported asset (which broke my project so i restored it from my backup), opened it and now my PATCH Admin window shows me, that i need to create an inital build.
I have my old (broken) project folder still on my harddrive. where are "settings" for patch located, so i can restore them?

**Comment by emanzione** [comment]
They are located next to the Assets folder, in a directory named `PATCHWorkspace`. You can copy the whole folder without issues.
![image](https://user-images.githubusercontent.com/5389049/162413032-a10f5bb4-6ee6-4151-96dd-256fbe13749d.png)
