### ISSUE TITLE
Feature Request: implement UpdateProgress.ProgressPercent property

### ISSUE THREAD

**Issue by DmitriyYukhanov** [emanzione/PATCH#51]
Would be great to have a property with percents out-of-the-box ^^

**Comment by emanzione** [comment]
Added the `Percentage` property in `UpdateProgress`! It will be available starting from the next version!

Commit ref: [36717c5c](https://gitlab.com/emanzione/mhlab.patch/-/commit/36717c5c31ec31ef966ee263ddf29c83644d1565)
