### ISSUE TITLE
Update Game when Build Index is newer on Server

### ISSUE THREAD

**Issue by LukasFratzl** [emanzione/PATCH#55]
Here, the current situation:
![2022-07-18 09_00_48-patch_bugs](https://user-images.githubusercontent.com/32310300/179459488-05509b1e-e3ce-4060-95c3-06eab36c9f53.jpg)

My Feature request is when doing this patch check and PATCH can't spot any updates, doing a Build Check and see if the current local game is lower as the version on the server, and create a repair when the server version is newer.
Maybe with a settings bool to enable or disable it.

**Comment by emanzione** [comment]
Done!
This can be enabled/disabled by setting the flag `ILauncherSettings.EnableRepairToTheLatestVersionIfNoPatchFound`. By default, it's enabled.

It will be included in the next release!
