### ISSUE TITLE
Is it possible to update the launcher to the latest version from earlier versions?

### ISSUE THREAD

**Issue by micromang** [emanzione/PATCH#58]
Is it possible to update the launcher to the latest version from earlier versions?
When I see the update design of the launcher, it seems that only the previous version of the launcher can be updated to the latest launcher. This is because update_index.json is the updated metadata between the previous launcher and the latest launcher. In other words, users who are using an older launcher can't update to the latest version of the launcher?

**Comment by emanzione** [comment]
They can totally update from any old version they have. The Launcher's update pipeline is different from the normal pipeline: it doesn't perform patching, instead it just replaces files.
So even in the case your Launcher is really old, it can simply download the latest available files and updates itself to the latest available version.
