### ISSUE TITLE
Allow passing custom headers to downloaders

### ISSUE THREAD

**Issue by DmitriyYukhanov** [emanzione/PATCH#59]
Hey, 

Currently, it's possible to pass the `NetworkCredential` only to set the `Authorization` header.
But sometimes other custom headers might be needed to properly authenticate.

Would be great to be able to pass any custom headers as well.

**Comment by emanzione** [comment]
This should be now possible with the new `ConfigureHttpRequest` method, added for #60 !
Let me know if that's not enough!
