### ISSUE TITLE
Allow overriding or extending built-in downloaders

### ISSUE THREAD

**Issue by DmitriyYukhanov** [emanzione/PATCH#60]
Hey,

It's great we can write completely own downloaders derived from `IDownloader`, but sometimes it's needed to modify / extend only one or few existing methods to achieve desired behavior. 

Thus, it would be nice to see more virtual methods in downloaders as well as more decomposed code to make it easier to override the default behavior.

For example, I'd be glad to be able to apply some custom settings to the constructed `request` before it gets passed to the `DownloaderHelper.GetResponse()`.

**Comment by emanzione** [comment]
I marked some additional methods with `virtual`, this should help!

Also, I added a new virtual `ConfigureHttpRequest` method, that gets called right after the creation of the web requests. This should highly enhance the customization experience!
