### ISSUE TITLE
Delete commands in Admin tool

### ISSUE THREAD

**Issue by Catsy73** [emanzione/PATCH#63]
Hi,

It would be nice to add two new commands to the admin command line tool to be able to delete properly an old build from the depot.
 - One to remove an full build entirely.
 - Another one to remove a patch.

Those commands would remove the right file and edit the index json automatically.

For example
.\MHLab.Patch.Admin.exe remove 0.1.0
.\MHLab.Patch.Admin.exe removePatch 0.1.0 0.1.1

It would allow easier automatization process if you want to keep only a fix number of build on your depot.

**Comment by emanzione** [comment]
Functionality added in the next release!
